services:

  api-service:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: api-service
    ports:
      - "9090:9090"
    depends_on: 
      db-service:
        condition: service-healthy

  db-service: 
    build:
      context: .
      dockerfile: services/db/Dockerfile
    container_name: db-service
    depends_on: 
      postgres:
        condition: service-healthy

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
