services:

  api-service:
    container_name: api-service
    build:
      context: ./../services/api
      dockerfile: ./Dockerfile
    ports:
      - "${API_SERVICE_EXTERNAL_PORT}:${API_SERVICE_INTERNAL_PORT}"
    environment:
      API_SERVICE_EXTERNAL_PORT: ${API_SERVICE_EXTERNAL_PORT}
      API_SERVICE_INTERNAL_PORT: ${API_SERVICE_INTERNAL_PORT}
      DB_SERVICE_INTERNAL_PORT: ${DB_SERVICE_INTERNAL_PORT}
    depends_on: 
      db-service:
        condition: service_started

  db-service: 
    container_name: db-service
    build:
      context: ./../services/db
      dockerfile: ./Dockerfile
    environment:
      DB_SERVICE_INTERNAL_PORT: ${DB_SERVICE_INTERNAL_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_TTL_SECONDS: ${REDIS_TTL_SECONDS}
    depends_on: 
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8-alpine

volumes:
  pgdata:
