services:

  api-service:
    container_name: api-service
    build:
      context: ./../services/api
      dockerfile: ./Dockerfile
    ports:
      - "${API_SERVICE_EXTERNAL_PORT}:${API_SERVICE_INTERNAL_PORT}"
    environment:
      GOPRIVATE: ${GOPRIVATE}
      DB_SERVICE_HTTP_SERVER_URL: ${DB_SERVICE_HTTP_SERVER_URL}
      API_SERVICE_EXTERNAL_PORT: ${API_SERVICE_EXTERNAL_PORT}
      API_SERVICE_INTERNAL_PORT: ${API_SERVICE_INTERNAL_PORT}
      GRPC_CLIENT_ADDR: ${GRPC_CLIENT_ADDR}
    depends_on: 
      db-service:
        condition: service_started

  db-service: 
    container_name: db-service
    build:
      context: ./../services/db
      dockerfile: ./Dockerfile
    environment:
      GOPRIVATE: ${GOPRIVATE}
      DB_SERVICE_INTERNAL_PORT: ${DB_SERVICE_INTERNAL_PORT}
      GRPC_SERVER_ADDR: ${GRPC_SERVER_ADDR}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on: 
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1 -p \"$POSTGRES_PORT\""]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  pgdata:
